### ISSUE TITLE
Admin Checklist

### ISSUE THREAD

**Issue by LeAlencar** [LeAlencar/wecommerce#24]
- [ ] Should be able to edit a product
- [ ] Should be able to register a product
- [ ] Should be able to see the checkout link of the product
- [ ] Should be able to inactivate or delete the product.
